In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('../data/Superstore.csv', encoding='latin-1')

In [2]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [3]:
print(df.shape)
print(df.columns.tolist())

# Transform Data Types

df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])

print(df.dtypes)

(9994, 21)
['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State', 'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit']
Row ID                    int64
Order ID                    str
Order Date       datetime64[us]
Ship Date        datetime64[us]
Ship Mode                   str
Customer ID                 str
Customer Name               str
Segment                     str
Country                     str
City                        str
State                       str
Postal Code               int64
Region                      str
Product ID                  str
Category                    str
Sub-Category                str
Product Name                str
Sales                   float64
Quantity                  int64
Discount                float64
Profit                  float64
dtype: object

In [4]:
# Rename columns for sql compatibility

df.columns = df.columns.str.replace(' ', '_').str.lower()
df.columns = df.columns.str.replace('-', '_').str.lower()

print(df.columns.tolist())

['row_id', 'order_id', 'order_date', 'ship_date', 'ship_mode', 'customer_id', 'customer_name', 'segment', 'country', 'city', 'state', 'postal_code', 'region', 'product_id', 'category', 'sub_category', 'product_name', 'sales', 'quantity', 'discount', 'profit']

In [5]:
print(df['profit'].describe())

count    9994.000000
mean       28.656896
std       234.260108
min     -6599.978000
25%         1.728750
50%         8.666500
75%        29.364000
max      8399.976000
Name: profit, dtype: float64

In [6]:
df.head()

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,postal_code,region,product_id,category,sub_category,product_name,sales,quantity,discount,profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

### Get all Negative Profit Count

In [7]:
df['profit'][df['profit'] < 0].describe()

count    1871.000000
mean      -83.448042
std       284.423422
min     -6599.978000
25%       -58.660950
50%       -18.088200
75%        -6.261500
max        -0.089500
Name: profit, dtype: float64

In [8]:
negative_profits = df.query("profit < 0")
negative_profits.loc[:, ['order_id', 'product_name', 'profit', 'discount']].head()

,order_id,product_name,profit,discount
3,US-2015-108966,Bretford CR4500 Series Slim Rectangular Table,-383.0310,0.45
14,US-2015-118983,Holmes Replacement Filter for HEPA Air Cleaner...,-123.8580,0.80
15,US-2015-118983,Storex DuraTech Recycled Plastic Frosted Binders,-3.8160,0.80
23,US-2017-156909,"Global Deluxe Stacking Chair, Gray",-1.0196,0.30
27,US-2015-150630,"Riverside Palais Royal Lawyers Bookcase, Royal...",-1665.0522,0.50

In [9]:
df['city'].isna().sum()

np.int64(0)

### Profit from each country

In [10]:
df.groupby(['region']).agg(
    total_profit=pd.NamedAgg(column='profit', aggfunc='sum'),
    average_profit=pd.NamedAgg(column='profit', aggfunc='mean'),
    order_count=pd.NamedAgg(column='order_id', aggfunc='count')
).reset_index()

    region  total_profit  average_profit  order_count
0  Central    39706.3625       17.092709         2323
1     East    91522.7800       32.135808         2848
2    South    46749.4303       28.857673         1620
3     West   108418.4489       33.849032         3203

In [11]:
# Derive useful columns
df['profit_margin'] = (df['profit'] / df['sales']) * 100
df['order_year'] = df['order_date'].dt.year
df['order_month'] = df['order_date'].dt.month
df['order_qarter'] = df['order_date'].dt.quarter
df['days_to_ship'] = (df['ship_date'] - df['order_date']).dt.days

In [12]:
# Check for issues
print("Hulls: ", df.isna().sum().sum())
print("Duplicates: ", df.duplicated().sum())
print("Negative profit: ", df[df['profit'] < 0].shape[0])

Hulls:  0
Duplicates:  0
Negative profit:  1871

In [13]:
# save cleaned csv

df.to_csv('../data/superstore_cleaned.csv', index=False)

In [3]:
print(df.shape)        # should be around (9994, 21)
print(df.memory_usage(deep=True).sum() / 1e6, "MB")

(9994, 21)
9.653723 MB

In [16]:
import sqlite3

In [17]:
df = pd.read_csv('../data/superstore_cleaned.csv')
conn = sqlite3.connect('sales.db')
df.to_sql('orders', conn, if_exists='replace', index=False)

9994